#ifndef HTTPSERVERHANDLER_H
#define HTTPSERVERHANDLER_H

#define HTTP_SERVER_PORT (80)

/** MUST BE CALLED AFTER A WIFI CONNECTION IS ENSTABILISHED */
void httpServerSetup();
void httpServerLoop();

#endif /* HTTPSERVERHANDLER_H */