#ifndef WIFISERVERHANDLER_H
#define WIFISERVERHANDLER_H

#define HOST_NAME "Host-Wirelessinator"
#define DELAY_BETWEEN_WIFI_CONNECTION_TRIALS (5000)

void wifiSetup();

#endif /* WIFISERVERHANDLER_H */