#ifndef SERVERHANDLER_H
#define SERVERHANDLER_H

#define SERVER_PORT (55555)
#define SERVER_MESSAGE_BUFFER_SIZE (1024)

/** MUST BE CALLED AFTER A WIFI CONNECTION IS ENSTABILISHED */
void serverSetup();
void serverLoop();

#endif /* SERVERHANDLER_H */